### ISSUE TITLE
Add docker build process for test automation 

### ISSUE THREAD

**Issue by jsirianni** [ssmiller25/thefortune#2]
Build a Dockerfile that will test the fortune file for duplicate entries, spelling, and the ability to compile.

**Comment by jsirianni** [comment]
Travis could be used to test, free for open source

**Comment by jsirianni** [comment]
I think this is resolved here https://github.com/ssmiller25/thefortune/blob/master/azure-pipelines.yml, different process same purpose

**Comment by ssmiller25** [comment]
👍
